# Generated by Django 5.2.8 on 2025-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_barangay_id_account_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
