# Generated by Django 5.2.8 on 2025-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_barangay_account_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
