# Generated by Django 5.2.6 on 2025-12-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_archived_at_medicine_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_orderable',
            field=models.BooleanField(default=True, help_text='Only non-prescription medicines can be ordered online'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='order_limit',
            field=models.CharField(choices=[('3_days', '3 Days Supply'), ('1_week', '1 Week Supply')], default='1_week', help_text='Maximum supply duration that can be ordered at once', max_length=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_type',
            field=models.CharField(choices=[('non_prescription', 'Non-Prescription (Over-the-Counter)'), ('prescription', 'Prescription Required')], default='non_prescription', help_text='Specify if this medicine requires a prescription', max_length=20),
        ),
    ]
