# Generated by Django 5.2.8 on 2025-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.CharField(blank=True, choices=[('Marco Dela Cruz', 'Marco Dela Cruz'), ('Johnrey Santos', 'Johnrey Santos'), ('Carlito Mendoza', 'Carlito Mendoza'), ('Jerome Villanueva', 'Jerome Villanueva'), ('Renzo Ramirez', 'Renzo Ramirez'), ('Gabriel Torres', 'Gabriel Torres'), ('Alfred Navarro', 'Alfred Navarro'), ('Kristoffer Soriano', 'Kristoffer Soriano'), ('Ralph Gutierrez', 'Ralph Gutierrez'), ('Leo Manalang', 'Leo Manalang')], max_length=255, null=True),
        ),
    ]
