# Generated by Django 5.2.8 on 2025-12-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['queue_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
