# Generated by Django 5.2.8 on 2025-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_order_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
