# Generated by Django 5.2.8 on 2025-12-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_queue_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='queue_number',
        ),
    ]
