# Generated by Django 5.2.8 on 2025-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
